### ISSUE TITLE
BadMethodException thrown for use of undefined method [package] in Laravel 5

### ISSUE THREAD

**Issue by ajaaibu** [thephpleague/color-extractor#27]
**Issue:**
In laravel 5 when the ServiceProvider is loaded it throws **BadMethodCallException** for use of undefined method [package].

**Fix:**
Commenting out the **boot()** section of the ServiceProvider works fine.

**Comment by MatTheCat** [comment]
I don't know anything about Laravel. Ping @toin0u, @GrahamCampbell

**Comment by toin0u** [comment]
@ajaaibu The service provider in the library is only for Laravel 4. Do you mind to make a pull request? :)

**Comment by ajaaibu** [comment]
@toin0u sorry i forgot to make the pull request after adding a fix on my fork, just now made the request :)

**Comment by moltar** [comment]
+1 (subbed)

**Comment by toin0u** [comment]
@moltar there is a merge request here: https://github.com/thephpleague/color-extractor/pull/28 :)

**Comment by GrahamCampbell** [comment]
:-1: for merging #28 it makes no sense to duplicate the service provider. #30 will fix this issue. There is literally no point in us even calling the package method. All that does is tell laravel where to look for the config and views, but we don't have any, and we missconfigured that package method anyway even if we did...

**Comment by toin0u** [comment]
@MatTheCat I agree with @GrahamCampbell :+1:
