### ISSUE TITLE
Could have better results?

### ISSUE THREAD

**Issue by sonu27** [thephpleague/color-extractor#29]
Using this [image](http://sonurai.com/wallpaper/SmoggyBeijing_ZH-CN10224762152.jpg) it gave me (in order):
- #364B84
- #FEA700
- #C37872
- #DEAC87
- #8C5155

Using [TinyLabs](http://labs.tineye.com/color/636ebd58a786b10773660f1dbf1b4f7debfc4d1d?ignore_background=True&width=250&color_format=hex&ignore_interior_background=True&height=156) I got:
- #af8fa7 36.4%
- #735873 21.4%
- #d2b2a8 19.8%
- #646a98 12.0%
- #453548 8.9%

I don't want to sound negative, but those results are much better. How can we improve this library to get more accurate colours?

**Comment by MatTheCat** [comment]
*color-extractor* doesn't extract most used colors from an image palette but most "vibrant" colors from all image colors. As these tools don't have the same goal it's normal there results are different.
