### ISSUE TITLE
Be able to pass in an image resource instead of image path.

### ISSUE THREAD

**Issue by zandzpider** [thephpleague/color-extractor#32]
Would be nice if i could pass an image stream, directly from memory instead of dumping the file to disk, and then process it via the color-extractor.

**Comment by MatTheCat** [comment]
Ping @philsturgeon I always wondered why you wrote the `Client` class this way!

**Comment by philsturgeon** [comment]
I probably wasn't thinking, change it!

**Comment by zandzpider** [comment]
Either throw in an filepath/string or an resource. yey =D

**Comment by MatTheCat** [comment]
Should I add only a `load` method or `loadResource` and `loadFile` (or both)?

**Comment by philsturgeon** [comment]
Probably make a new Resource or File class, with methods that accept various formats, or something.

Ask on the mailing list perhaps, I'm crap at this.

--
Phil Sturgeon
