### ISSUE TITLE
Allow to retrieve `hsl` or `cmyk` from a color ?

### ISSUE THREAD

**Issue by shulard** [thephpleague/color-extractor#39]
Hello,

This piece of code is really cool :)
Do you think it can be interesting to add methods in the `Color` object to mutate from RGB to HSL or even CMYK ?

If so I can make a PR :smile:

Thanks !

**Comment by MatTheCat** [comment]
Hello and thanks ^^

I avoided a color object to limit the memory footprint and keep the scope narrow, so I don't plan to add such conversion methods.
That being said I'm pretty sure these methods exist in another libraries.

**Comment by shulard** [comment]
Thanks for your feedback :+1:
