### ISSUE TITLE
Alpha channel of .png is taken into account

### ISSUE THREAD

**Issue by RomainSauvaire** [thephpleague/color-extractor#42]
Hello and congratulations for this nice piece of code !

I am trying to work with some .png files and this one particularly fails and returns me `#000000` as the most vibrant color.
<img width="173" alt="capture d ecran 2016-03-17 a 20 38 32" src="https://cloud.githubusercontent.com/assets/1195119/13858767/5d9f266a-ec80-11e5-845f-8b295a66449a.png">

I guess it fetches it from the alpha channel.

Could you have a more in-depth look please ? Here is the image
![interval_contentsc](https://cloud.githubusercontent.com/assets/1195119/13858786/796ee574-ec80-11e5-913a-c99f7d3cb4cf.png)

**Comment by MatTheCat** [comment]
Hi!

You're right I don't take alpha channel into account. I think I should blend transparent colors considering a white background.

But for some reason I can't reproduce the behavior you describe using the image above neither can I create such image =/

**Comment by RomainSauvaire** [comment]
Hi Mat,

I guess GH transforms uploaded images. Here is a "raw" version. 

My bet would be to count it as a "special" color that don't get mixed with the others : on this particular image I would like to retrieve a dark yellow rather than the transparent/white. Do you see what I mean ?
Let me know if you need something else.

[interval_contentsc.png.zip](https://github.com/thephpleague/color-extractor/files/179225/interval_contentsc.png.zip)

**Comment by al35mm** [comment]
What I do on my system is that when someone uploads an image, a small temporary duplicate is created as a sample, say 100px x 100px. That duplicate is used for the color extraction. That speeds the process up massively, but what you can do before the color extraction step, is add a background color, say white, to your small sample image. That way there will never be any alpha to worry about and color extractor will always return colors. Your full size image will still have alpha, but your script will now define that as white.

**Comment by MatTheCat** [comment]
@RomainSauvaire this is what I get with your last image:

![colors](https://cloud.githubusercontent.com/assets/1898254/13886401/f3613272-ed36-11e5-877b-92fda99608b2.png)

Maybe our GD version are differents? I've got 2.1.1-3.

@al35mm as resizing affect colors I prefer not to do that. However you can resize an image for yourself before building the palette.

**Comment by RomainSauvaire** [comment]
@MatTheCat I have 2.1.1-dev. Doesn't look so far than yours. But I have complete different results (with the original file)
<img width="161" alt="capture d ecran 2016-03-21 a 11 24 53" src="https://cloud.githubusercontent.com/assets/1195119/13915900/a0d01afa-ef57-11e5-9346-4c12842e2309.png">

I'm a little bit lost here :-/

**Comment by MatTheCat** [comment]
This may seem dumb but are you sure it's the right image and the color-extractor version you're using is 0.2.0?

**Comment by RomainSauvaire** [comment]
This doesn't seem dumb ;)

Here is the version filled in my composer.json
```
"league/color-extractor": "^0.2.0"
```

The image URL I use is filled in an image `src` to check it is the correct one so yeah, I guess it is :)

<img width="635" alt="capture d ecran 2016-03-21 a 11 46 16" src="https://cloud.githubusercontent.com/assets/1195119/13916391/a6955330-ef5a-11e5-994d-0d9d97fe3d6b.png">

FYI here is the code I use
```PHP
$url = 'whatever';

echo '<img src="'.$url.'">';

$palette = Palette::fromFilename($url);
$palette = $palette->getMostUsedColors(5);

foreach($palette as $color => $count) {
      $c = Color::fromIntToHex($color);
      echo  '<div style="background-color:'.$c.'; display: inline-block;width: 2rem;height: 2rem;"></div>';
}
```

**Comment by MatTheCat** [comment]
Oh I assumed you used the `ColorExtractor::extract` but you just get the most used colors. Would it be correct to consider full transparency as white or just ignore it?

**Comment by RomainSauvaire** [comment]
Ok I got the difference between `mostUsed` and `extract`. Thank you for the clarification.

IMHO, it is not correct to consider _transparent_ as a color either _white_ or whatever. It should not be counted at all. But I don't know if it is feasible.

**Comment by MatTheCat** [comment]
I think I'll introduce two more parameters in `Palette` constructors: `$ignoreTransparency`, defaulting to `true` and `$transparencyColor` defaulting to `16777215` (white). The latter will be used to blend colors if transparency is taken into account.

**Comment by RomainSauvaire** [comment]
Nice idea @MatTheCat.

I'm thinking of a way to rather define a `$transparencyColor` (or anything else) which will be defaulted to `null` and can be replaced by a color when we want it to be blended.

What do you think about that ?

**Comment by MatTheCat** [comment]
It's simpler, I'll do that.

Maybe `$backgroundColor` would be better for such a variable?

**Comment by RomainSauvaire** [comment]
Why not but there is no info about the fact that it will override transparency. I hesitate but I'm not sure to propose a better naming.

ps: ce serait plus simple en français ;)

**Comment by MatTheCat** [comment]
Okay ^^

Si cette couleur "remplace" la transparence alors qu'advient-il des pixels semi-transparents ? Je pense que l'idée d'un "fond" est plus intuitive puisque tout se passera comme si le fond de l'image était de cette couleur.

**Comment by RomainSauvaire** [comment]
Excellent argument : je n'avais pas pensé au semi-transparent ;)
