### ISSUE TITLE
Request: is it possible for the library to offer sorting the colours light to dark?

### ISSUE THREAD

**Issue by u01jmg3** [thephpleague/color-extractor#46]
- Is it possible for the library to offer sorting the colours light to dark?

e.g. https://gist.github.com/alexkingorg/2158428

**Comment by MatTheCat** [comment]
Have you tried using `ksort` on `getIterator()` return?

**Comment by u01jmg3** [comment]
Sorry for the slow reply.

How would I use that with this?

```php
$image_path = 'cv.png';
$palette    = Palette::fromFilename($image_path);
$colours    = $palette->getMostUsedColors(6);
```

**Comment by MatTheCat** [comment]
Convert colors into HSL color space and then you'll be able to sort them by L.
Such a functionality is outside the scope of this lib.
