### ISSUE TITLE
Call to undefined function

### ISSUE THREAD

**Issue by marijang** [thephpleague/color-extractor#47]
FatalThrowableError in Palette.php line 54:
Call to undefined function League\ColorExtractor\imagecreatefromstring()

**Comment by marijang** [comment]
and how to implement into laravel 5.3

**Comment by MatTheCat** [comment]
> FatalThrowableError in Palette.php line 54:
Call to undefined function League\ColorExtractor\imagecreatefromstring()

How do you have managed to install it without GD?

> and how to implement into laravel 5.3

Whatever the framework you just have to implement one or two classes.

**Comment by marijang** [comment]
I have php7 on centos
yum install yum install php70w-gd

**Comment by marijang** [comment]
ok i got it thanks:D

**Comment by MatTheCat** [comment]
Well I don't see how you could have GD enabled without having `imagecreatefromstring`.

What do

```bash
composer show -p | grep gd
```

and

```
php -m | grep gd
```

show?

**Comment by mpoppell** [comment]
I'd say he did what I just did and forgot to restart php after enabling gd. Just for future ref.
