### ISSUE TITLE
Doesn't work with Laravel 5.5

### ISSUE THREAD

**Issue by vertizontical** [thephpleague/color-extractor#50]
I installed via Composer, then added the following to my config/app.php file:

'provider' => [
......
League\ColorExtractor\Laravel\ColorExtractorServiceProvider::class,
],

'aliases' => [
.......
'ColorExtractor' => League\ColorExtractor\Laravel\ColorExtractorFacade::class,
],

But I get the following error:
Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Class 'League\ColorExtractor\Laravel\ColorExtractorServiceProvider' not found

**Comment by MatTheCat** [comment]
Where do you see Laravel mentionned in the README? Since 0.2 you don't need any provider.
