### ISSUE TITLE
Undefined offset error

### ISSUE THREAD

**Issue by Asedol** [thephpleague/color-extractor#54]
Dude, fix getColorCount in Palette class. Something like this:
`public function getColorCount($color)
    {
        if(array_key_exists($color, $this->colors)) {
            return $this->colors[$color];
        }
        return 0;
    }`

**Comment by colinodell** [comment]
Fixed in [v0.4.0](https://github.com/thephpleague/color-extractor/releases/tag/0.4.0) via 21fcac6.  Thanks for the report!
