### ISSUE TITLE
Webp image is not supported

### ISSUE THREAD

**Issue by roelvanhintum** [thephpleague/color-extractor#55]
When feeding imagecreatefromstring a webp image, the following error occurs.
```
imagecreatefromstring(): Data is not in a recognized format in /var/www/html/vendor/league/color-extractor/src/League/ColorExtractor/Palette.php:54
```

**Comment by gimler** [comment]
From the php documentation http://php.adamharvey.name/manual/en/function.imagecreatefromstring.php
```
7.3.0 | WEBP is supported now (if supported by the libgd in use).
```

I have added a PR to test webp support
