### ISSUE TITLE
cpu Usage 20-30%

### ISSUE THREAD

**Issue by Mr-houzi** [thephpleague/color-extractor#61]
cpu Usage 20-30%，How to solve？

**Comment by colinodell** [comment]
Extracting colors is a resource-intensive process as we must check each pixel and then perform a bunch of complex math to get the results.  Unfortunately there's not much we can do about this, and 20-30% usage during execution isn't actually too bad.

If you (or anyone else) have ideas for performance improvements please feel free to submit a PR!
