### ISSUE TITLE
Map int result to strings.

### ISSUE THREAD

**Issue by alexvais** [thephpleague/color-extractor#63]
Hi,

I want to map the Int result that give me this library to for example:

red
green
back
white

To create a basic filter of image main color.
covering all the range of colors.

How can i do it?

**Comment by katesaikishore** [comment]
Yeah expecting the same from here?
@alexvais Got any solution?

**Comment by MatTheCat** [comment]
You can look at https://github.com/thephpleague/color-extractor/blob/3336395cb0396ddb6cc2f3a2b13b28682ed484ed/src/League/ColorExtractor/Color.php#L33  to extract red, green and blue component.
